# Generated by Django 3.0.11 on 2021-01-29 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog1', '0002_temp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Temp',
        ),
    ]
